#Only for development purpose
FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm config set registry http://registry.npmjs.org/
RUN npm set strict-ssl false
RUN npm install

COPY . .

CMD ["npm", "run", "start"]